create table fcity.T_Provider(
	providerId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	providerName VARCHAR(255) NOT NULL,
	EMail VARCHAR(255) NOT NULL,
	IsVerified INTEGER  NOT NULL,
	CreatedOn TIMESTAMP NOT NULL,
	LastLogOn TIMESTAMP ,
CONSTRAINT verified_range CHECK (IsVerified in (0,1)));
